<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div class="copyright-box">
        <span class="copyright-text"><?= $block->escapeHtml($block->getCopyright()) ?></span>
        <div class="copyright-image"><img class="custom-img" src="<?php echo $this->getViewFileUrl('images/copyright.png'); ?>"></div>
    </div>
</small>
