<div class="custom-page-bottom">
    <div class="carousel-wrap">
        <div class="owl-carousel">
            <div class="item">
                <img class="custom-item-image" src="<?php echo $this->getViewFileUrl('images/naruto.jpeg'); ?>">
                <p class="custom-item-text">Nulla porttitor accumsan tincidunt. Donec rutrum congue leo eget malesuada.
                    Donec sollicitudin
                    molestie malesuada. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Curabitur arcu
                    erat, accumsan id imperdiet et, porttitor at sem.</p>
                <h4 class="custom-item-title"><a class="custom-item-title-link">NARUTO</a></h4>
                <p class="custom-item-small-text"><a class="custom-item-text-link">Fashion Shop</a></p>
            </div>
            <div class="item">
                <img class="custom-item-image" src="<?php echo $this->getViewFileUrl('images/sasuke.jpeg'); ?>">
                <p class="custom-item-text">Nulla porttitor accumsan tincidunt. Donec rutrum congue leo eget malesuada.
                    Donec sollicitudin
                    molestie malesuada. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Curabitur arcu
                    erat, accumsan id imperdiet et, porttitor at sem.</p>
                <h4 class="custom-item-title"><a class="custom-item-title-link">SASUKE</a></h4>
                <p class="custom-item-small-text"><a class="custom-item-text-link">Fashion Shop</a></p>
            </div>
            <div class="item">
                <img class="custom-item-image" src="<?php echo $this->getViewFileUrl('images/kakashi.jpeg'); ?>">
                <p class="custom-item-text">Nulla porttitor accumsan tincidunt. Donec rutrum congue leo eget malesuada.
                    Donec sollicitudin
                    molestie malesuada. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Curabitur arcu
                    erat, accumsan id imperdiet et, porttitor at sem.</p>
                <h4 class="custom-item-title"><a class="custom-item-title-link">KAKASHI</a></h4>
                <p class="custom-item-small-text"><a class="custom-item-text-link">Fashion Shop</a></p>
            </div>
        </div>
    </div>
    <div class="custom-page-bottom-small-content">
        <div class="custom-page-bottom-small-content-box">
            <div class="custom-page-bottom-small-content-box-image">
                <img class="custom-page-bottom-small-content-image"
                     src="<?php echo $this->getViewFileUrl('images/category-1.png'); ?>">
            </div>
            <a class="custom-page-bottom-small-content-title-link"><h3>Milk & Flavoured</h3></a>
            <div class="custom-page-bottom-small-content-box-text">
                <a class="custom-page-bottom-small-content-text-link"><p>Exotic Fruits & Veggies</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Fruits</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Vegetables</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Herbs & Seasonings</p></a>
            </div>
        </div>
        <div class="custom-page-bottom-small-content-box">
            <div class="custom-page-bottom-small-content-box-image">
                <img class="custom-page-bottom-small-content-image"
                     src="<?php echo $this->getViewFileUrl('images/category-2.png'); ?>">
            </div>
            <a class="custom-page-bottom-small-content-title-link"><h3>Sour Cream and Dips</h3></a>
            <div class="custom-page-bottom-small-content-box-text">
                <a class="custom-page-bottom-small-content-text-link"><p>Exotic Fruits & Veggies</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Fruits</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Vegetables</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Herbs & Seasonings</p></a>
            </div>
        </div>
        <div class="custom-page-bottom-small-content-box">
            <div class="custom-page-bottom-small-content-box-image">
                <img class="custom-page-bottom-small-content-image"
                     src="<?php echo $this->getViewFileUrl('images/category-3.png'); ?>">
            </div>
            <a class="custom-page-bottom-small-content-title-link"><h3>Liquor Cabinet</h3></a>
            <div class="custom-page-bottom-small-content-box-text">
                <a class="custom-page-bottom-small-content-text-link"><p>Exotic Fruits & Veggies</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Fruits</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Vegetables</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Herbs & Seasonings</p></a>
            </div>
        </div>
        <div class="custom-page-bottom-small-content-box">
            <div class="custom-page-bottom-small-content-box-image">
                <img class="custom-page-bottom-small-content-image"
                     src="<?php echo $this->getViewFileUrl('images/category-4.png'); ?>">
            </div>
            <a class="custom-page-bottom-small-content-title-link"><h3>Marmalades</h3></a>
            <div class="custom-page-bottom-small-content-box-text">
                <a class="custom-page-bottom-small-content-text-link"><p>Exotic Fruits & Veggies</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Fruits</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Vegetables</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Herbs & Seasonings</p></a>
            </div>
        </div>
        <div class="custom-page-bottom-small-content-box" style="border: none">
            <div class="custom-page-bottom-small-content-box-image">
                <img class="custom-page-bottom-small-content-image"
                     src="<?php echo $this->getViewFileUrl('images/category-5.png'); ?>">
            </div>
            <a class="custom-page-bottom-small-content-title-link"><h3>Kitchen Cabinets</h3></a>
            <div class="custom-page-bottom-small-content-box-text">
                <a class="custom-page-bottom-small-content-text-link"><p>Exotic Fruits & Veggies</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Fruits</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Fresh Vegetables</p></a>
                <a class="custom-page-bottom-small-content-text-link"><p>Herbs & Seasonings</p></a>
            </div>
        </div>
    </div>
    <div class="custom-page-bottom-big-content">
        <h2 class="custom-page-bottom-big-content-title">Our Latest News</h2>
        <div class="custom-page-bottom-big-content-box">
            <div class="custom-page-bottom-big-content-item">
                <img class="custom-page-bottom-big-content-image"
                     src="<?php echo $this->getViewFileUrl('images/blog-1.jpeg'); ?>">
                <ul class="custom-page-bottom-big-content-item-text">
                    <li class="custom-page-bottom-big-content-item-text-special">LIFE STYLE</li>
                    <li>BINH DONGVAN</li>
                    <li>JAN 03. 2021</li>
                </ul>
                <a class="custom-page-bottom-big-content-item-title"><h3> Let's show off stronger with Salmon, Fruits & Seafoods </h3></a>
            </div>
            <div class="custom-page-bottom-big-content-item">
                <img class="custom-page-bottom-big-content-image"
                     src="<?php echo $this->getViewFileUrl('images/blog-2.jpeg'); ?>">
                <ul class="custom-page-bottom-big-content-item-text">
                    <li class="custom-page-bottom-big-content-item-text-special">NEWS</li>
                    <li>JONY JOHAN</li>
                    <li>JAN 03. 2021</li>
                </ul>
                <a class="custom-page-bottom-big-content-item-title"><h3> Avocado Grilled Salmon, Rich In Nutrients For The Body </h3></a>
            </div>
            <div class="custom-page-bottom-big-content-item">
                <img class="custom-page-bottom-big-content-image"
                     src="<?php echo $this->getViewFileUrl('images/blog-3.jpeg'); ?>">
                <ul class="custom-page-bottom-big-content-item-text">
                    <li class="custom-page-bottom-big-content-item-text-special">NEWS</li>
                    <li>JONY JOHAN</li>
                    <li>JAN 03. 2020</li>
                </ul>
                <a class="custom-page-bottom-big-content-item-title"><h3> Summer Breakfast For The Healthy Morning With Tomatoes </h3></a>
            </div>
            <div class="custom-page-bottom-big-content-item">
                <img class="custom-page-bottom-big-content-image"
                     src="<?php echo $this->getViewFileUrl('images/blog-4.jpeg'); ?>">
                <ul class="custom-page-bottom-big-content-item-text">
                    <li class="custom-page-bottom-big-content-item-text-special">NEWS</li>
                    <li>JONY JOHAN</li>
                    <li>JAN 03. 2020</li>
                </ul>
                <a class="custom-page-bottom-big-content-item-title"><h3> Popular Reasons You Must Drinks Juice Everyday </h3></a>
            </div>
        </div>
    </div>
</div>
